#!/bin/sh
# gen-embedded-install-self-block.sh — emit write_embedded_install for curl-pipe self-copy.
# Invoked by scripts/assemble-install.sh after init/uninstall regions are spliced.

set -e

ROOT=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
INSTALL_SH="${ROOT}/install.sh"
BEGIN_MARKER='# ASSEMBLE:INSTALL_SELF_BEGIN'
END_MARKER='# ASSEMBLE:INSTALL_SELF_END'

[ -f "$INSTALL_SH" ] || { echo "ERROR: missing ${INSTALL_SH}" >&2; exit 1; }

PAYLOAD=$(mktemp)
trap 'rm -f "$PAYLOAD"' EXIT

awk -v beg="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == beg { skip = 1; next }
    skip && $0 == end { skip = 0; next }
    skip { next }
    { print }
' "$INSTALL_SH" >"$PAYLOAD"

cat <<'HEADER'
# GENERATED by scripts/assemble-install.sh — DO NOT EDIT
# Authoring input: install.sh (excluding INSTALL_SELF region)

HEADER

printf '%s() {\n' write_embedded_install
printf '    _dest="$1"\n'
printf '    cat > "$_dest" << '"'"'EDGELET_INSTALL_SELF_EOF'"'"'\n'
cat "$PAYLOAD"
printf '%s\n' EDGELET_INSTALL_SELF_EOF
printf '    chmod 755 "$_dest"\n'
printf '}\n'
