#!/bin/sh
# gen-embedded-uninstall-block.sh — emit embedded uninstall writer for install.sh monolith.
# Invoked by scripts/assemble-install.sh; not run at install time.

set -e

ROOT=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
SRC="${ROOT}/uninstall.sh"

[ -f "$SRC" ] || { echo "missing embed source: ${SRC}" >&2; exit 1; }

cat <<'HEADER'
# GENERATED by scripts/assemble-install.sh — DO NOT EDIT
# Authoring input: uninstall.sh

HEADER

printf '%s() {\n' write_embedded_uninstall
printf '    _dest="$1"\n'
printf '    cat > "$_dest" << '"'"'EDGELET_UNINSTALL_EOF'"'"'\n'
cat "$SRC"
printf '%s\n' EDGELET_UNINSTALL_EOF
printf '    chmod 755 "$_dest"\n'
printf '}\n'
