FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN apk add --no-cache util-linux

CMD ["/bin/sh", "-c", "nsenter --target 1 --mount --uts --ipc --net -- sleep 14000"]