currentProfile: development
profiles:
    development:
        arch: auto
        availableDiskThreshold: "20"
        caCert: ""
        changeFrequency: "10"
        controllerCert: /Users/emirhan/Documents/GitHub/Agent/agent-go/dev/etc/iofog-agent/cert.crt
        controllerUrl: http://localhost:51121/api/v3
        devMode: "on"
        deviceScanFrequency: "60"
        diskConsumptionLimit: "10"
        diskDirectory: /Users/emirhan/Documents/GitHub/Agent/agent-go/dev/var/lib/iofog-agent/
        dockerPruningFrequency: "0"
        dockerUrl: unix:///var/run/docker.sock
        edgeGuardFreq: "0"
        edgeGuardFrequency: "0"
        getChangesFreq: "60"
        gps: auto
        gpsCoordinates: 0,0
        gpsDevice: /dev/ttyUSB0
        gpsMode: auto
        gpsScanFreq: "60"
        gpsScanFrequency: "60"
        iofogUuid: db36ff94-2533-4189-9c5d-eee38199d918
        isolatedDockerContainer: "off"
        logDiskConsumptionLimit: "10.0"
        logDiskDirectory: /Users/emirhan/Documents/GitHub/Agent/agent-go/dev/var/log/iofog-agent/
        logFileCount: "10"
        logLevel: DEBUG
        memoryConsumptionLimit: "4096"
        namespace: datasance
        networkInterface: dynamic
        postDiagnosticsFreq: "10"
        privateKey: eyJjcnYiOiJFZDI1NTE5IiwiZCI6ImFpc0VTTFdVNFRwYUk1ZWxPM2c3LU1Cd2JGS3dTbnY4ZHFJckpxT214Y3ciLCJ4IjoiVkQyNENoQzROaXprb19jRk83U2JBdXFGZVBoc1FhemlmRVdUbkVqUlJFQSIsImt0eSI6Ik9LUCJ9
        processorConsumptionLimit: "80.0"
        routerHost: ""
        routerPort: ""
        routerUuid: ""
        scanDevicesFreq: "60"
        secureMode: "off"
        statusFrequency: "10"
        statusUpdateFreq: "30"
        timeZone: Etc/UTC
        tlsCert: ""
        tlsKey: ""
        upgradeScanFrequency: "24"
        watchdogEnabled: "true"
