description "Edgelet daemon"
author "Datasance"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 20 300

exec /usr/local/bin/edgelet daemon >> /var/log/edgelet/daemon.log 2>&1
