#!/bin/sh /etc/rc.common
# Edgelet control plane (OpenWrt procd)

START=99
STOP=10
USE_PROCD=1

start_service() {
    /usr/local/bin/edgelet cgroup-preflight || return $?

    procd_open_instance
    procd_set_param command /usr/local/bin/edgelet
    procd_append_param command daemon
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    /usr/libexec/edgelet/edgelet-shutdown
}
